name:                sh2md
version:             0.1.0.0
github:              "kkweon/sh2md"
license:             BSD3
author:              "Mo Kweon"
maintainer:          "kkweon@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Record your shell session and print in the markdown format
category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kkweon/sh2md#readme>

dependencies:
- base >= 4.7 && < 5
- Hclip                >= 3.0.0 && < 3.1
- transformers         >= 0.5.5 && < 0.6
- process              >= 1.6.3 && < 1.7
- unix                 >= 2.7.2 && < 2.8
- containers           >= 0.5.11 && < 0.6
- optparse-applicative >= 0.14.3 && < 0.15
- text                 >= 1.2.3 && < 1.3

library:
  source-dirs: src

executables:
  sh2md:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -O3
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sh2md

tests:
  sh2md-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sh2md
