name:                record-shell-to-markdown
version:             0.1.0.0
github:              "kkweon/record-shell-to-markdown"
license:             BSD3
author:              "Mo Kweon"
maintainer:          "kkweon@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kkweon/record-shell-to-markdown#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  record-shell-to-markdown-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - record-shell-to-markdown

tests:
  record-shell-to-markdown-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - record-shell-to-markdown
